### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by sunithapatel** [frontendstudygroup/frontendstudygroup.github.io#10]
Design landing page that gives a small description of what this site is for.
(Some suggestions in issue #1)

**Comment by IngridFuentes** [comment]
Can I be assigned this one? Thanks

**Comment by sunithapatel** [comment]
@IngridFuentes I assigned this to you. Please post a sample of what you are thinking to do and we can discuss here. Thank you!

**Comment by IngridFuentes** [comment]
Of course. Thank you!

**Comment by princiya** [comment]
@IngridFuentes no pressure, but if you need help we are there on slack to discuss and help you out. 😄 🙌

**Comment by IngridFuentes** [comment]
Hello. Thank you! I'm sharing what I have so far. Please check out the figma file and let me know your thoughts and also what else I can add or change. Thanks!
https://www.figma.com/file/DCUjvP9jfDaE2LYottcJZl/Home-page-WWC?node-id=0%3A1

**Comment by sunithapatel** [comment]
This looks really nice! The header has already been done, so make sure you sync your fork with the latest changes.

So for this issue you would do that middle portion in your screenshot there. 
@princiya on the home page should we have anything about this is a project being worked on by WWC Front End or something like that? Or what is in this screenshot is good enough for this?

I would suggest to remove the email newsletter portion since we won't be doing that now.

I think the footer portion with the social media links could be another component. 
@princiya @favour-chibueze I saw you brought up about social media links in #11. Should we consider creating another issue for a footer to have social media links? This could always be at the bottom no matter what page we are on.

**Comment by IngridFuentes** [comment]
Awesome! Thank you @sunithapatel. Yes, anything else just let me know @princiya

**Comment by princiya** [comment]
@IngridFuentes good job 👏 .
Like Sunitha mentioned already, header component has been done already.
Also for footer, I created a new issue which has been claimed too. #28.
So what you can do is, write a React component for the middle part that you designed on Figma.
To begin with, it can be static content like what you have in the Figma file.
As a next issue, you or someone else can work on showing some random facts or tweets or messages related to opensource, frontend etc.

**Comment by IngridFuentes** [comment]
@princiya Thank you! I'll work on that and keep you guys updated.

**Comment by stephanieopala** [comment]
Hello, I am working on this issue. Design and implementation of the About Page #39
