### ISSUE TITLE
Deploy React App to AWS with AWS Amplify

### ISSUE THREAD

**Issue by sunithapatel** [frontendstudygroup/frontendstudygroup.github.io#18]
Since this is a static website we can use AWS Amplify to deploy this site to AWS.

Some documentation from Create React App:
https://create-react-app.dev/docs/deployment#aws-amplify

We do not have an AWS account yet, so you would have to use your own account to test this out - potentially with AWS free tier.

Suggestion - might be good to document the steps you took (through console or infrastructure as code) and add it to this repository - maybe in a deployment folder as a markdown file?

**Comment by harrylongia** [comment]
I do not have a working AWS account and also this would be my first time deploying on AWS. Answering your question, I can work on front-end development but also I would love to learn and work on new areas.

**Comment by sunithapatel** [comment]
@harrylongia In order to work on this issue, you would need an AWS account of your own. 

If you are okay with creating your own AWS account for learning, you could fork this repository and use the app to deploy it to AWS Amplify following the instructions from the documentation linked in the issue. 

Then there are two options with this:
1. Create a pull request to this repository with any files used for deployment, along with a markdown file explaining how to set this up - which we could then use once we are able to see how to get some sort of account for this repository.
2. Create a pull request to our frontend blog repository with a blog post going through the steps you did to deploy the app to AWS. This is a different repository here: https://github.com/frontendstudygroup/blog

Or both! 😄

**Comment by furixturi** [comment]
Hi, I can work on this with my AWS account. 
Please assign the issue to me if @harrylongia is okay.

**Comment by harrylongia** [comment]
@furixturi go ahead mate. I don't have any problem.

**Comment by sunithapatel** [comment]
> Hi, I can work on this with my AWS account.
> Please assign the issue to me if @harrylongia is okay.

Thank you so much @furixturi! I assigned it to you. Let me know if you have any questions!

**Comment by furixturi** [comment]
Hi, I created a walk through markdown doc showing the steps of deploying React App to AWS with AWS Amplify. 
The PR is #65
