### ISSUE TITLE
Set up continuous integration with GitHub Actions

### ISSUE THREAD

**Issue by sunithapatel** [frontendstudygroup/frontendstudygroup.github.io#19]
Include GitHub actions yml file to build and deploy the React app after every merge to master.

Can also include a step to build and run tests the app on every pull request and block merge if build or tests fail.

**Comment by princiya** [comment]
Thanks @sunithapatel for creating this issue.

Following our slack conversation what I forgot to mention in the readme is the following:

> if you could trigger `npm run deploy` when code is merged into `master` and setup Github actions that would be awesome.

`npm run deploy` step in package.json [link](https://github.com/frontendstudygroup/frontendstudygroup.github.io/blob/master/package.json#L19)

`gh-pages` is a devDependency which takes care of building the app, putting the build into the `gh-pages` branch and invoke github pages to do the right thing.
[link](https://github.com/frontendstudygroup/frontendstudygroup.github.io/blob/master/package.json#L40)
