### ISSUE TITLE
Design the header

### ISSUE THREAD

**Issue by princiya** [frontendstudygroup/frontendstudygroup.github.io#2]

**Comment by ToluAdegboyega** [comment]
I'd like to implement an header component with a responsive navbar. I have created the attached image with Canva to give a visual idea. Feedback is highly appreciated. @sunithapatel @princiya 

![Frontend Study Group](https://user-images.githubusercontent.com/65776842/135671594-6bf77e74-f601-44e7-91c7-167b08887ecc.png)

**Comment by sunithapatel** [comment]
Wow, looks good @ToluAdegboyega! @princiya would it be okay to change "Products" to "Resources" since that page will have the  list of internships under it?

**Comment by ToluAdegboyega** [comment]
Thank you! I'll get started and I can make any requested changes along the way. 

Unfortunately, I've been unable to assign the issue to myself. Please help.

**Comment by sunithapatel** [comment]
Thank you so much! I assigned it to you now.

**Comment by favour-chibueze** [comment]
![Screenshot (248)](https://user-images.githubusercontent.com/46398983/135726794-2867dcbb-34cf-441b-9798-835fe91297b8.png)
@ToluAdegboyega @sunithapatel Thinking of implementing this on the mobile view. Do you think it's cool?

**Comment by ToluAdegboyega** [comment]
Yes! @favour-chibueze. I think it adds a nice touch.

**Comment by favour-chibueze** [comment]
Okay. @ToluAdegboyega

**Comment by sunithapatel** [comment]
@favour-chibueze I agree, looks nice! ❤️
