### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by princiya** [frontendstudygroup/frontendstudygroup.github.io#3]
How to contribute:

- Fork the repo (recommended if you are the first time)
- Claim the issue
- If the issue is not there, create a new issue
- Make sure the issue has been assigned to you
- Comment in the issue about your approach to solving the problem
- Get feedback from others
- Submit a PR when you are ready

**Comment by sunithapatel** [comment]
This is great! Maybe at the end we can add a point about joining the FrontEnd Slack group to ask any general questions. 

Would it be okay to add this as a section named How To Contribute in the main README file?
