### ISSUE TITLE
Design About Page

### ISSUE THREAD

**Issue by stephanieopala** [frontendstudygroup/frontendstudygroup.github.io#39]
Design the About page for the site.

**Comment by stephanieopala** [comment]
@sunithapatel I am still researching on how to implement the section with the repository. For now, I can work on the section on the right once Princiya also approves.

**Comment by princiya** [comment]
@stephanieopala great design 🚀 .
for the section on right, for now, just implement a static section where you can hard-code the information you have as per the design.
when your PR is merged, as a next step, if you are interested to learn or implement API related stuff, you can use github API to get that repository information.

**Comment by princiya** [comment]
fixed #43
