### ISSUE TITLE
Improve information displayed for resources

### ISSUE THREAD

**Issue by RossellaFer** [frontendstudygroup/frontendstudygroup.github.io#45]
I think a nice addition would be to display a description for each specific resource. Also, since we have gathered this data from a single website, it would be nice to add a disclaimer at the end of the Resources and individual resources pages a reference to this site.

So I think we can create a Disclaimer component, to be used both in the Resources and Single Resource component.

Since I was working on the Resources component, I have noticed that the last row is cut by the footer, so I thought we could change the fixed height of the grid articles in order to make all content visible.

**Comment by princiya** [comment]
fixed #46
