### ISSUE TITLE
Homepage UI

### ISSUE THREAD

**Issue by anushkachauhxn** [frontendstudygroup/frontendstudygroup.github.io#62]
URL: https://frontendstudygroup.github.io/

Hi,

I'm not sure if the home page is supposed to look like this. It seems pretty inconsistent. 
Also, the **Start** Button is not clickable.

Is this a deployment error?

![Screenshot (162)](https://user-images.githubusercontent.com/59930625/142973534-89ad3b28-49dd-4181-be8c-718d551ab23d.png)

**Comment by princiya** [comment]
Hi Anushka. Yes, this is how it is. This was a community effort and folks learning to work in public for the first time participated here for Hacktoberfest.
The aim was to learn to collaborate, and not focus on making this fully functional.
If you are interested, feel free to propose design changes and we can have a nice landing page.
Thank you for checking this out :)

**Comment by princiya** [comment]
Also, there is an open issue where folks are working on the re-design, incase you want to collaborate with them. :) 
- https://github.com/frontendstudygroup/frontendstudygroup.github.io/issues/56
