### ISSUE TITLE
Deploy React App with Azure Static WebApps

### ISSUE THREAD

**Issue by sunithapatel** [frontendstudygroup/frontendstudygroup.github.io#9]
To learn about deployment to Azure, since this is a React app, we can deploy it using Azure Static WebApps.

Potentially can set up GitHub actions for this. 
Azure DevOps is another tool I am familiar with, but that could be a separate issue to integrate that.

Link to documentation from Create React App:
https://create-react-app.dev/docs/deployment#azure

Link to documentation from Azure:
https://docs.microsoft.com/en-us/azure/static-web-apps/getting-started?tabs=react

NOTE: We do not yet have an Azure account to use for this, but you could sign up for a free one (with credit card) and use the free tier for this.
If you are a student, you can sign up for an account without a credit card: 
https://azure.microsoft.com/en-us/free/students/

**Comment by priyankarki** [comment]
Can I be assigned this issue?

**Comment by sunithapatel** [comment]
Awesome! I assigned it to you. Let me know if you need help with any of it.
